### ISSUE TITLE
Still can't use methods from require(./../globals.js)

### ISSUE THREAD

**Issue by avmakesthings** [avmakesthings/temple360#12]
-tried adding module.export etc but not working
-very confuse

**Comment by avmakesthings** [comment]
it would be much easier to setup a global namespace but not sure how to do that with JS ?

**Comment by daveeloo** [comment]
If this is for the browser, the window object is the global namespace. So if `window.whatever = 3`, you should be able to call `whatever` from anywhere and it will return `3`.

**Comment by avmakesthings** [comment]
sorry I meant set up a custom namespace for the variables/ methods i want available globally

**Comment by daveeloo** [comment]
You could do `window.myNamespace = {}` and then add variables/methods to `myNamespace`.
